name: Manual Deploy

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to deploy'     
        required: true
        default: 'development'
        type: choice
        options: ['development', 'qa', 'qa1', 'production', 'E', 'F' ]
      Branch:
        description: 'Enter the name of the branch to be deployed'
        required: true
        default: 'rc-34'
      

jobs:
  
  UUID:
    name: UUID
    runs-on: ubuntu-latest
    environment:
      name: deployment-env    
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: Get the uuid
        id: uuid
        run: | 
            echo "::set-output name=uuid::$(uuidgen)"
            echo "## :round_pushpin: ${{ github.event.inputs.Branch }} Branch >> ${{ github.event.inputs.Environment }} Environment" >> $GITHUB_STEP_SUMMARY

  DEPLOYER:
    name: deployer
    runs-on: ubuntu-latest
    steps:
      - name: deploy checkerrrr 
        uses: aptyInc/deployment-check-actions@main
        id: neverquit
        with:
          BRANCH_NAME: "${{github.event.inputs.Branch}}"
          ENVIRONMENT_NAME: "${{github.event.inputs.Environment}}"
          BUCKET_NAME: "test-fh-dynamic-partitions-s3"
          SERVICE_NAME: "newTest"
          REGION: "us-east-1"
          TARGET_BRANCH: "${{github.event.pull_request.base.ref}}"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      


  
  