name: Manual Deploy

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to deploy'     
        required: true
        default: 'development'
        type: choice
        options: ['development', 'qa', 'qa1', 'staging']
      Branch:
        description: 'Enter the branch name to be deployed'
        required: true
        default: 'rc-34'

jobs:
  
  UUID:
    name: UUID
    runs-on: ubuntu-latest
    environment:
      name: deployment-env    
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: Get uuid
        id: uuid
        run: | 
            echo "::set-output name=uuid::$(uuidgen)"
            echo "## :round_pushpin: ${{ github.event.inputs.Branch }} Branch >> ${{ github.event.inputs.Environment }} Environment" >> $GITHUB_STEP_SUMMARY

  rules:
    name: Rules
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.validations.outputs.branch_name }}
      should_deploy: ${{ steps.validations.outputs.should_deploy}}
      non_prod_deploy: ${{ steps.validations.outputs.non_prod_deploy}}
      prod_deploy: ${{ steps.validations.outputs.prod_deploy}}
    steps:
      - name: Fetch Branch Name
        uses: aptyInc/gha-branch-name
        id: validations

  DEPLOYER:
    name: deployer
    runs-on: ubuntu-latest
    needs: [rules]
    steps:
      - name: deploy checkerrrr 
        uses: vishvajeet-apty/deployment-check-actions@main
        id: depender
        with:
          BRANCH_NAME: "${{needs.rules.outputs.branch_name}}"
          BUCKET_NAME: "apty-bundle-watch/apty-assist"
          REGION: "us-east-1"
          CONFIG_PATH: "./"
          TARGET_BRANCH: ${{github.event.pull_request.base.ref}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  