name: Manual_Deploy_GHAssist
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
        type: choice
        options: ['development', 'qa', 'qa1', 'staging', 'production']
      Branch:
        description: 'Enter branch name which is to be deployed'
        required: true
        default: 'rc-'
jobs:
  rules:
    name: Rules
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.validations.outputs.branch_name }}
      should_deploy: ${{ steps.validations.outputs.should_deploy}}
      non_prod_deploy: ${{ steps.validations.outputs.non_prod_deploy}}
      prod_deploy: ${{ steps.validations.outputs.prod_deploy}}
    steps:
      - name: Fetch Branch Name
        uses: vishvajeet-apty/deployment-check-actions@main
        id: validations
      - name : printing values
        run: echo "the name of the branch is ${{steps.validations.outputs.branch_name}}"
      - name : v
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} "

  checkerrr:
    name: Checkerrr
    runs-on: ubuntu-latest 
    needs : [rules]
    steps:
      - name: Check the deployment array
        uses: vishvajeet-apty/deployment-check-actions@main
        id: valid
      - with:
          BRANCH_NAME: ${{needs.rules.outputs.branch_name}}
          BUCKET_NAME: "apty-bundle-watch/apty-assist"
          REGION: "us-east-1"
          CONFIG_PATH: "./player3.0/bundle.config.json"
          TARGET_BRANCH: ${{github.event.pull_request.base.ref}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  