name: Manual Deploy

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to deploy'     
        required: true
        default: 'development'
        type: choice
        options: ['development', 'qa', 'qa1', 'staging']
      Branch:
        description: 'Enter branch name to be deployed'
        required: true
        default: 'development'

jobs:
  UUID:
    name: UUID
    runs-on: ubuntu-latest
    environment:
      name: deployment-env    
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: Get uuid
        id: uuid
        run: | 
            echo "::set-output name=uuid::$(uuidgen)"
            echo "## :round_pushpin: ${{ github.event.inputs.Branch }} Branch >> ${{ github.event.inputs.Environment }} Environment" >> $GITHUB_STEP_SUMMARY
  
  